### POST PRODUCT_HEADQUARTER
POST http://localhost:3000/headquarter/productHeadquarter
Content-Type: application/json

{
    "_stock":6,
    "_idHeadquarter":"6129c85483df9e42f027015a",
    "_idProduct":"6129cabd855b8b08e4fc6db1"
}

### PUT PRODUCT_HEADQUARTER BY ID PRODUCT HEADQUARTER
PUT http://localhost:3000/headquarter/productHeadquarter/updateById/6129c88f7514310114e4d105
Content-Type: application/json

{
    "_stock":6
}

### GET PRODUCTS_HEADQUARTER BY BRAND, CATEGORY AND SIZE
### http://localhost:3000/headquarter/productHeadquarter/readByBrandCategorySize/:_idHeadquarter/:_idBrand/:_idCategory/:_idSize
GET http://localhost:3000/headquarter/productHeadquarter/readByBrandCategorySize/6129c85483df9e42f027015a/null/6127329d92f54b32dc73b21d/612732e592f54b32dc73b224

### GET PRODUCTS_HEADQUARTER
GET http://localhost:3000/headquarter/productHeadquarter

### GET FULL PRODUCTS 
GET http://localhost:3000/headquarter/productHeadquarter/full/6129c85483df9e42f027015a


<<<<<   DATA TESTING   >>>>>
    "_stock":2,
    "_idHeadquarter":"612549559619d14e5459f229",
    "_idProduct":"612548739619d14e5459f211"
