### POST PRICE
POST http://localhost:3000/price/price
Content-Type: application/json

{
    "_amount" : 16,
    "_idKindPrice":"61462fccbfd0421fa0b00650",
    "_idProduct":"61274514be557958acee78a2"
}


### GET FULL PRICES BY _IDPRODUCT
### http://localhost:3000/price/price/readFullPrices/:_idProduct
GET http://localhost:3000/price/price/readFullPrices/61274514be557958acee78a2

### GET PRICE
GET http://localhost:3000/price/price



<<<<<   DATA TESTING   >>>>>
    <   KindPrice = menor  >
    "_amount" : 20,
    "_idKindPrice":"",
    "_idProduct":""

    <   KindPrice = mayor  >
    "_amount" : 18,
    "_idKindPrice":"",
    "_idProduct":""

    <   KindPrice = priviligiado  >
    <   priviligiado no se basa en ninguno
    de los tipso de precios definidos por un
    liminte inferior y superior, no importa 
    la cantidad, aplica cualquier cantidad  >
    "_amount" : 18,
    "_idKindPrice":"",
    "_idProduct":""