### POST DETAIL_SALE_ORDER
POST http://localhost:3000/saleOrder/detailSaleOrder
Content-Type: application/json

{
    "_price": 17,
    "_amount": 1,
    "_idProductHeadquarter": "6129ca45612ef93a24211614",
    "_idSaleOrder": "61252606ca64d0458cec3577"
}


### GET DETAILS_SALE_ORDER
GET http://localhost:3000/saleOrder/detailSaleOrder/6128af108084fc1a80a4ffb7