### POST CATEGORIES
POST http://localhost:3000/product/category
Content-Type: application/json

{
    "_name": "Camisa"
}


### GET CATEGORIES
GET http://localhost:3000/product/category

<<<<<   DATA TESTING   >>>>> 
    "_name": "Polo"
    "_name": "Pantalon"
    "_name": "Camisa"